<?php	echo $this->render('sub-header.phtml'); ?>
        <dl class="row videoList">
                        <dd class="col-md-4 col-xs-12 friends">
                            <div class="fri-bb clearfix">
                                 <img src="/Front/img/avatar-img.png"> 
                                 <h1>Raj Sharma</h1>
                                 <p>University of Clombo</p>
                               </div>
                           </dd>
                           
                           <dd class="col-md-4 col-xs-12 friends">
                            <div class="fri-bb clearfix">
                                 <img src="/Front/img/avatar-img2.png"> 
                                 <h1>Heather Sturgeon</h1>
                                 <p>University of Clombo</p>
                               </div>
                           </dd>
                           
                           <dd class="col-md-4 col-xs-12 friends">
                            <div class="fri-bb clearfix">
                                 <img src="/Front/img/avatar-img3.png"> 
                                 <h1>Andy Bickle</h1>
                                 <p>University of Clombo</p>
                               </div>
                           </dd>
                           
                           <dd class="col-md-4 col-xs-12 friends">
                            <div class="fri-bb clearfix">
                                 <img src="/Front/img/avatar-img.png"> 
                                 <h1>Raj Sharma</h1>
                                 <p>University of Clombo</p>
                               </div>
                           </dd>
                           
                           <dd class="col-md-4 col-xs-12 friends">
                            <div class="fri-bb clearfix">
                                 <img src="/Front/img/avatar-img2.png"> 
                                 <h1>Heather Sturgeon</h1>
                                 <p>University of Clombo</p>
                               </div>
                           </dd>
                           
                           <dd class="col-md-4 col-xs-12 friends">
                            <div class="fri-bb clearfix">
                                 <img src="/Front/img/avatar-img3.png"> 
                                 <h1>Andy Bickle</h1>
                                 <p>University of Clombo</p>
                               </div>
                           </dd>
                           
                           <dd class="col-md-4 col-xs-12 friends">
                            <div class="fri-bb clearfix">
                                 <img src="/Front/img/avatar-img.png"> 
                                 <h1>Raj Sharma</h1>
                                 <p>University of Clombo</p>
                               </div>
                           </dd>
                           
                           <dd class="col-md-4 col-xs-12 friends">
                            <div class="fri-bb clearfix">
                                 <img src="/Front/img/avatar-img2.png"> 
                                 <h1>Heather Sturgeon</h1>
                                 <p>University of Clombo</p>
                               </div>
                           </dd>
                           
                           <dd class="col-md-4 col-xs-12 friends">
                            <div class="fri-bb clearfix">
                                 <img src="/Front/img/avatar-img3.png"> 
                                 <h1>Andy Bickle</h1>
                                 <p>University of Clombo</p>
                               </div>
                           </dd>
                           
                           <dd class="col-md-4 col-xs-12 friends">
                            <div class="fri-bb clearfix">
                                 <img src="/Front/img/avatar-img.png"> 
                                 <h1>Raj Sharma</h1>
                                 <p>University of Clombo</p>
                               </div>
                           </dd>
                           
                           <dd class="col-md-4 col-xs-12 friends">
                            <div class="fri-bb clearfix">
                                 <img src="/Front/img/avatar-img2.png"> 
                                 <h1>Heather Sturgeon</h1>
                                 <p>University of Clombo</p>
                               </div>
                           </dd>
                           
                           <dd class="col-md-4 col-xs-12 friends">
                            <div class="fri-bb clearfix">
                                 <img src="/Front/img/avatar-img3.png"> 
                                 <h1>Andy Bickle</h1>
                                 <p>University of Clombo</p>
                               </div>
                           </dd>
                           
                           <dd class="col-md-4 col-xs-12 friends">
                            <div class="fri-bb clearfix">
                                 <img src="/Front/img/avatar-img.png"> 
                                 <h1>Raj Sharma</h1>
                                 <p>University of Clombo</p>
                               </div>
                           </dd>
                           
                           <dd class="col-md-4 col-xs-12 friends">
                            <div class="fri-bb clearfix">
                                 <img src="/Front/img/avatar-img2.png"> 
                                 <h1>Heather Sturgeon</h1>
                                 <p>University of Clombo</p>
                               </div>
                           </dd>
                           
                           <dd class="col-md-4 col-xs-12 friends">
                            <div class="fri-bb clearfix">
                                 <img src="/Front/img/avatar-img3.png"> 
                                 <h1>Andy Bickle</h1>
                                 <p>University of Clombo</p>
                               </div>
                           </dd>
                           
                           
                       </dl>