<?php	if(is_array($records) && count($records) > 0) {
			foreach($records as $key => $value) {	?>
	<dd class="col-md-6 col-xs-12 videoFrame big-head">
		<div class="row">
        	<div class="col-xs-12 col-md-12">
            	<div class="video"><img src="http://img.youtube.com/vi/<?php echo $this->customurl($value['media_url'], 'fetchYoutubeID'); ?>/0.jpg" title="<?php echo $value['media_title']; ?>" alt="<?php echo $value['media_title']; ?>"></div>
			</div>
            <div class="col-xs-12 col-md-12">
            	<h4><a title="<?php echo $value['media_title']; ?>" href="<?php	echo $this->url('front', array('controller' => 'search', 'action' => 'view-video', 'id' => base64_encode((string)$value['_id']))); ?>"><?php echo $value['media_title']; ?></a></h4>
				<div class="row">                                        
                   	<div class="col-xs-12 pull-left">
                       	<p><span>Last viewed:</span> Sunday, December 5th, 2013</p>
                           <p><span>Seen:</span> 5 Times</p>
					</div>
				</div>
			</div>
              	<div class="col-xs-12 col-md-12">
               	<div class="face-com">
                   	<p><span>Leave Comment</span></p>
                       <img src="/Front/img/fb-com.png" alt="">
				</div>
			</div>                                
		</div>
	</dd>
<?php		}
			if(($totalRecords - ($page * 2)) > 0) {	?>
				<dd class="clearfix pri-nextbtn">
			    	<a class="btn btn-pri" href="#">Previous</a>
			        <a class="btn btn-default" href="#">Next</a>
				</dd>
<?php		} else { ?>
				<dd class="clearfix pri-nextbtn">
			    	<a class="btn btn-pri" href="#">Previous</a>
			        <a class="btn btn-next" href="#">Next</a>
				</dd>
<?php		}
		}	?>
    
