<?php	if(is_array($records) && count($records) > 0) {	?>
<h3 class="recom-h3 visible-xs">Recommended Videos</h3>
<dd class="col-md-5 col-xs-12 col-lg-4">
<?php		$recommendedVideos	= array_splice($records, 0, 3);
			foreach($recommendedVideos as $key => $value) { ?>
	<div class="recom-videos">
       	<a title="<?php echo $value['media_title']; ?>" href="<?php	echo $this->url('front', array('controller' => 'search', 'action' => 'view-video', 'id' => base64_encode((string)$value['_id']))); ?>">
			<img src="http://img.youtube.com/vi/<?php echo $this->customurl($value['media_url'], 'fetchYoutubeID'); ?>/0.jpg" alt="<?php echo $value['media_title']; ?>">
			<span class="play-btn"><i class="fa fa-play fa-2"></i></span>
		</a>
	</div>
	<h4><a title="<?php echo $value['media_title']; ?>" href="<?php	echo $this->url('front', array('controller' => 'search', 'action' => 'view-video', 'id' => base64_encode((string)$value['_id']))); ?>"><?php	echo $this->text($value['media_title'], 25, 'displayText'); ?></a></h4>
	<div class="row videoFrame">
       	<div class="col-md-4 col-xs-3 pull-right">
           	<ul class="likes">
               	<li>
                   	<a class="like" href="#" onclick='dovote(1, "<?php	echo base64_encode((string)$value['_id']); ?>", "<?php echo $value['media_title']; ?>");return false;'><i class="fa fa-2x fa-thumbs-up"></i></a>
				</li>
                   <li>
                   	<a class="dislike" href="#" onclick='dovote(2, "<?php	echo base64_encode((string)$value['_id']); ?>", "<?php echo $value['media_title']; ?>");return false;'><i class="fa fa-2x fa-thumbs-down"></i></a>
				</li>
			</ul>
		</div>
           <div class="col-md-8 col-xs-9 pull-left recom-videos">
           	<ul class="users"> 
               	<li><a href="#"><img height="30" width="30" title="user name" alt="user" src="/Front/img/user01.jpg"></a></li>
                   <li><a href="#"><img height="30" width="30" title="user name" alt="user" src="/Front/img/user02.jpg"></a></li>
                   <li><a href="#"><img height="30" width="30" title="user name" alt="user" src="/Front/img/user03.jpg"></a></li>
                   <li><a href="#"><img height="30" width="30" title="user name" alt="user" src="/Front/img/user02.jpg"></a></li>
                   <li><a href="#"><img height="30" width="30" title="user name" alt="user" src="/Front/img/user03.jpg"></a></li>
			</ul> 
		</div>
	</div>
<?php		}
			if($totalRecords > 3) { ?>
	<a href="<?php	echo $this->url('front', array('controller' => 'search', 'action' => 'view-recommended')); ?>" class="btn btn-link">more videos</a>
<?php		}	?>
</dd>
<?php	} ?>