<?php	echo $this->render('sub-header.phtml');
		$youtubeID	= $this->customurl($videoArray['media_url'], 'fetchYoutubeID');
		$videoTitle	= $videoArray['media_title'];
		$description= $videoArray['media_description'];
		$encodedID	= base64_encode((string)$videoArray['_id']);
		$autoplay	= 0;
		if(MAILER) {
			$autoplay	= 1;
		}	?>
	<style type="text/css">
		.at16nc, .at300bs {
			background: none;
		}
	</style>
	<h3 class="page-title visible-xs"><?php	echo $videoTitle; ?></h3>

	<!--Desktop view-->
	<div class="row hidden-xs" id="title_segment">
    	<h2 class="page-title col-md-7 col-lg-8"><?php	echo $videoTitle; ?></h2>
        
	</div>
    <!--Desktop view-->
	<dl class="row contribute-video" id="video_segment">

                       		<dd class="col-md-7 col-lg-8 col-xs-12 videoFrame big-head">

                                <div class="row">
                                    <div class="col-xs-12 col-md-12">
                                        <div class="videoview">
                                            <iframe src="http://youtube.com/embed/<?php	echo $youtubeID; ?>?rel=0&wmode=transparent&autoplay=<?php	echo $autoplay; ?>" frameborder="0" allowfullscreen></iframe>
                                        </div>
                                    </div>
                                    <div class="col-xs-12 col-md-12">    
                                        <div class="row">
                                        	<div class="col-md-6 col-xs-12">
                                                <span class="note">Length: 4.32</span>
                                                <ul class="users"> 
                                                    <li><a href="#"><img height="30" width="30" title="user name" alt="user" src="/Front/img/user01.jpg"></a></li>
                                                    <li><a href="#"><img height="30" width="30" title="user name" alt="user" src="/Front/img/user02.jpg"></a></li>
                                                    <li><a href="#"><img height="30" width="30" title="user name" alt="user" src="/Front/img/user03.jpg"></a></li>
                                                    <li><a href="#"><img height="30" width="30" title="user name" alt="user" src="/Front/img/user02.jpg"></a></li>
                                                    <li><a href="#"><img height="30" width="30" title="user name" alt="user" src="/Front/img/user03.jpg"></a></li>
                                                </ul> 
                                                                                               
                                            </div>                                            
                                            <div class="col-md-3 col-xs-6">
                                                <span class="note">Share</span>
                                                <ul class="s-share">
                                                    <li><a href="#" onclick="shareonfb('<?php	echo FB_APPID; ?>', '<?php	echo $videoTitle; ?>', '<?php	echo $videoTitle; ?>', '<?php echo DOMAINPATH.'/front/search/view-video/'.$encodedID; ?>', '<?php echo $description; ?>', 'http://img.youtube.com/vi/<?php	echo $youtubeID; ?>/0.jpg', '<?php	echo REDIRECT_URL; ?>');" class="icon-fb"></a></li>
													<li><a href="#" class="icon-twitter addthis_button_twitter"></a></li>
                                                </ul>
                                            </div>
                                            <div class="col-md-3 col-xs-6">
                                                <ul class="likes">
                                                    <li style="margin-right:10px;">
                                                        <span class="note">247</span>
                                                        <a class="like" href="#" onclick='dovote(1, "<?php	echo $encodedID; ?>", "<?php	echo $videoTitle; ?>");return false;'><i class="fa fa-2x fa-thumbs-up"></i></a>
                                                    </li>
                                                    <li>
                                                        <span class="note">10</span>
                                                        <a class="dislike" href="#" onclick='dovote(2, "<?php	echo $encodedID; ?>", "<?php	echo $videoTitle; ?>");return false;'><i class="fa fa-2x fa-thumbs-down"></i></a>
                                                    </li>
                                                </ul>
                                            </div>
                                            
                                        </div>
                                    </div>
                                    
                                    <div class="col-xs-12 col-md-12">
                                        <div class="contribute" style="margin-top:10px;">
											<button class="add-playbtn">Add to Playlist</button>
                                            <p><span>Description: </span></p>
                                            <p><?php	echo $description; ?></p>
                                        </div>
                                    </div>
                                    
                                    <div class="col-xs-12 col-md-12">
                                        <div class="face-com" style="padding-top:0;">
											
                                            <p><span>Leave Comment</span></p>
											<div class="fb-comments" data-href="http://snapstate.sdiphp.com/front/index/index" data-numposts="5" data-colorscheme="light" data-mobile="false"></div><!-- http://snapstate.sdiphp.com/front/search/<?php	//echo base64_encode((string)$videoArray['_id']); ?> -->
                                        </div>
                                    </div>
                                    
                                </div>
                                
                            </dd>
                            
							
                       
                    	</dl>
<script type="text/javascript">
	var addthis_share = {
		templates : {
			twitter : "Friends, Check it out '<?php echo $videoTitle; ?>' video in Snapstate.com - <?php echo DOMAINPATH.'/front/search/view-video/'.$encodedID; ?>"
		}
	}
</script>
<script type="text/javascript" src="https://s7.addthis.com/js/300/addthis_widget.js#pubid=xa-516d13f2076fbb6e"></script>
<script type="text/javascript">
	$(document).ready(function(){
		/*	if($('#title_segment').length) {
			
		}	*/
		
		if($('#video_segment').length) {
			$.get('/front/search/recommended-videos', function(data){
				if($.trim(data) != '') {
					$('#video_segment').append(data);
					$('#title_segment').append('<h3 class="col-md-5 recom-h3 col-lg-4">Recommended Videos</h3>');
				}
			});
		}
	});
</script>