<?php	echo $this->render('fo-header.phtml');
		//	Session
		use Zend\Session\Container;
		$userSession	= new Container('fo_user');
		$listingSession	= new Container('fo_listing');	?>
    <body class="home-page">
		<div id="fb-root"></div>
		<!-- <div id="bodydiv"> -->
    	<!--View in Desktop--->
        <div class="visible-lg">
        	<div class="navbar navbar-fixed-top">
            	<div class="container">
                	<div class="navbar-header">
                    	<a class="navbar-brand" href="/"><img src="<?php	echo SITE_IMAGE_PATH; ?>snapstate-logo.png" alt="SnapState Logo"></a> 
                        
<?php	if(isset($userSession->userSession['_id']) && $userSession->userSession['_id'] != '') {	?>
						<div class="navbar-login navbar-right dropdown">
                            <a class="btn btn-primary dropdown-toggle" href="#" data-toggle="dropdown" version="3">My Account<b class="caret"></b></a>                
                            <ul aria-labelledby="drop3" role="menu" class="dropdown-menu">
                                <li role="presentation"><a href="#" tabindex="-1" role="menuitem" data-toggle="modal" data-target="#edit_profile_popup" onclick="resetProfileForm();"><i class="fa fa-edit"></i>Edit Profile</a></li>
                                <li class="divider" role="presentation"></li>
                                <li role="presentation"><a href="#" tabindex="-1" role="menuitem"><i class="fa fa-list-alt"></i>Play List</a></li>
                                <li class="divider" role="presentation"></li>
                                <li role="presentation"><a href="#" tabindex="-1" role="menuitem"><i class="fa fa-video-camera"></i>Videos Watched</a></li>
                                <li class="divider" role="presentation"></li>
                                <li role="presentation"><a href="<?php	echo $this->url('front', array('controller' => 'index', 'action' => 'logout')); ?>" onclick="showOverlay();" tabindex="-1" role="menuitem"><i class="fa fa-power-off"></i>Logout</a></li>
                          </ul>
                        </div>
						
<?php	} else {	?>
						<div class="navbar-login navbar-right"><a class="btn btn-primary visible-lg" data-toggle="modal" data-target="#login">Login</a></div>
<?php	}	?>
						<form class="navbar-form navbar-left visible-lg" method="post" id="search_form" name="search_form" action="<?php	echo $this->url('front', array('controller' => 'search', 'action' => 'search')); ?>">
                            <div class="form-group">
                                <input type="text" id="navsearch" placeholder="search" class="form-control" name="search" value="<?php	if(isset($listingSession->keyword) && trim($listingSession->keyword) != '') { echo $listingSession->keyword; } ?>">
								<button type="submit" class="btn btn-success searchSubmit"></button>
                            </div>        
                        </form>
                	</div>
                </div>
            </div>
         </div>
         
         <div class="jumbotron visible-lg">
            <div class="container">
                <h1><span class="size100 bold">Snap</span> Yourself into State</h1>
<?php	if(!isset($userSession->userSession['_id']) || $userSession->userSession['_id'] == '') {	?>
                <p class="normal margintop30">We put your videos first. That means we don’t put ads before, after,<br>or over your videos.</p>
                <p><a class="btn btn-primary btn-lg" data-toggle="modal" data-target="#signup" >FREE Signup!</a></p>
<?php	} ?>
            </div>
        </div>
        
        <div class="flexCont">
        
        <aside class="asideNav hidden-lg">
            <div class="sideBanner">
                <div class="bannerIn">
                    <h3><strong>snap</strong> yourself into state</h3>
                    <p>We put your videos first. That<br> means we don’t put ads before,<br> after, or over your videos.</p>
<?php	if(!isset($userSession->userSession['_id']) || $userSession->userSession['_id'] == '') {	?>
                    <a href="#" class="btn btn-default" data-toggle="modal" data-target="#signup">FREE Sign up!</a>
<?php	} ?>
                </div>
            </div>
            <ul>
                        <li>
                            <h1 class="active"><a href="javascript:void(0)" ><i class="fa fa-2x icon-friends"></i> Friends</a></h1>
                        </li>                
                        <li>
                            <h1 class="arrow-drop"><a href="javascript:void(0)"><i class="fa fa-2x icon-filter"></i> Filter</a></h1>
							<ul class="dd-sel">
								<li>Seen:
								<span class="drop-dwn-arr8 wid-100"> 
									<select class="sel-box">
										<option>Select</option>
										<option>Never</option>	
										<option>< week</option>
										<option>< month</option>
										<option>< 3 months</option>
										<option>>3 months</option>
									</select>
								</span>
								</li>
								
                                <li>Friend:
								<span class="drop-dwn-arr8 wid-100"> 
									<select class="sel-box">
										<option>Select</option>
										<option>Yes</option>	
										<option>No</option>
									</select>
								</span>
								</li>
								
								<li>Length:
								<span class="drop-dwn-arr8 wid-100"> 
									<select class="sel-box">
										<option>Select</option>
										<option>< 1 minutes</option>	
										<option>< 2 minutes</option>
										<option>< 5 minutes</option>
										<option>> 5 minutes</option>
									</select>
								</span>
								</li>
								
								<li>Category:
								<span class="drop-dwn-arr8 wid-100"> 
									<select class="sel-box">
										<option>Select</option>
										<option>Health</option>	
										<option>Funny</option>
										<option>Motivational</option>
									</select>
								</span>
								</li>
								
								<li>Ranking:
								<span class="drop-dwn-arr8 wid-100"> 
									<select class="sel-box">
										<option>Select</option>
										<option>< 4 stars</option>	
										<option>> 4 stars</option>
									</select>
								</span>
								</li>
                            </ul>
                        </li>
                        <li> 
                            <h1><a href="javascript:void(0)"><i class="fa fa-2x icon-share"></i> Share</a></h1>
                        </li>               
                        <li> 
                            <h1><a href="javascript:void(0)"><i class="fa fa-2x icon-upload"></i> Contribute</a></h1>
                        </li>
                        <li> 
                            <h1><a href="javascript:void(0)"><i class="fa fa-2x icon-feedback"></i> Feedback</a></h1>
                        </li>
                        <li> 
                            <h1><a href="javascript:void(0)"><i class="fa fa-2x icon-like"></i> Like / Dislike</a></h1>
                        </li>
                    </ul>
        </aside>
        
        <div class="flexDiv">
            <div class="navbar navbar-fixed-top hidden-lg">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>

                        <a class="navbar-brand" href="/"><img src="<?php	echo SITE_IMAGE_PATH; ?>snapstate-logo@2x.png" alt="SnapState Logo"></a> 

                        <a class="navbar-search" href="#"><span class="fa fa-2x fa-search"></span> <span class="fa fa-2x fa-times"></span></a> 
                    </div>
                    <form class="navbar-form" method="post" id="search_form_mini" name="search_form_mini" action="<?php	echo $this->url('front', array('controller' => 'search', 'action' => 'search')); ?>">
                        <div class="form-group">
                            <div class="searchSm">
                                <input type="text" id="navsearch2" placeholder="search" class="form-control" name="search" value="<?php	if(isset($listingSession->keyword) && trim($listingSession->keyword) != '') { echo $listingSession->keyword; } ?>">
								<button type="submit" class="btn btn-success searchSubmit"></button>
                            </div>

                        </div>        
                    </form>
                </div>
            </div>

            <main class='SCROLLER_FRAME'>
                <div class='SCROLLER'>
                    <div class="container">
                        <div class="row">
                        	<aside class="col-lg-3 asideNav visible-lg">
                    <ul>
                        <li>
                            <h1 class="active"><a href="javascript:void(0)" ><i class="fa fa-2x icon-friends"></i> Friends</a></h1>
                        </li>                
                        <li>
                            <h1 class="arrow-drop"><a href="javascript:void(0)"><i class="fa fa-2x icon-filter"></i> Filter</a></h1>
							<ul class="dd-sel">
                                <li>Seen:
								<span class="drop-dwn-arr8 wid-100"> 
									<select class="sel-box">
										<option>Select</option>
										<option>Never</option>	
										<option>< week</option>
										<option>< month</option>
										<option>< 3 months</option>
										<option>>3 months</option>
									</select>
								</span>
								</li>
								
                                <li>Friend:
								<span class="drop-dwn-arr8 wid-100"> 
									<select class="sel-box">
										<option>Select</option>
										<option>Yes</option>	
										<option>No</option>
									</select>
								</span>
								</li>
								
								<li>Length:
								<span class="drop-dwn-arr8 wid-100"> 
									<select class="sel-box">
										<option>Select</option>
										<option>< 1 minutes</option>	
										<option>< 2 minutes</option>
										<option>< 5 minutes</option>
										<option>> 5 minutes</option>
									</select>
								</span>
								</li>
								
								<li>Category:
								<span class="drop-dwn-arr8 wid-100"> 
									<select class="sel-box">
										<option>Select</option>
										<option>Health</option>	
										<option>Funny</option>
										<option>Motivational</option>
									</select>
								</span>
								</li>
								
								<li>Ranking:
								<span class="drop-dwn-arr8 wid-100"> 
									<select class="sel-box">
										<option>Select</option>
										<option>< 4 stars</option>	
										<option>> 4 stars</option>
									</select>
								</span>
								</li>
                            </ul>
							
                        </li>
                        <li> 
                            <h1><a href="javascript:void(0)"><i class="fa fa-2x icon-share"></i> Share</a></h1>
                        </li>               
                        <li> 
                            <h1><a href="javascript:void(0)"><i class="fa fa-2x icon-upload"></i> Contribute</a></h1>
                        </li>
                        <li> 
                            <h1><a href="javascript:void(0)"><i class="fa fa-2x icon-feedback"></i> Feedback</a></h1>
                        </li>
                        <li> 
                            <h1><a href="javascript:void(0)"><i class="fa fa-2x icon-like"></i> Like / Dislike</a></h1>
                        </li>
                    </ul>
                </aside><!-- /Sidebar -->
                            
				<!-- Elements are loaded from sub-herder.phtml in views -->
				
<?php	echo $this->content; ?>
                </div>
                        </div>
                    </div>
                    <!-- /container -->
<?php	echo $this->render('fo-footer.phtml'); ?>
