<?php	echo $this->render('leftnav.phtml'); ?>
<?php	if(isset($this->message) && trim($this->message) != '') {
			$display	= 'display:block;';
		} else {
			$display	= 'display:none;';
		}
		$messageClass	= 'alert-success';
		if(isset($this->errorMessage) && trim($this->errorMessage) == '1') {
			$messageClass	= 'alert-error';
		}	?>
			<div>
				<ul class="breadcrumb">
					<li>
						<a href="<?php	echo $this->url('cms', array('controller' => 'index', 'action' => 'index')); ?>">Home</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="#">Site Settings</a>
					</li>
				</ul>
			</div>
			<div class="row-fluid">
				<div class="box span12">
					<div class="box-header well" data-original-title style="cursor:pointer;">
						<h2><i class="icon-th"></i> Site Settings</h2>
						<div class="box-icon">
						</div>
					</div>
					<div class="box-content">
<?php	$form = $this->siteSettingsForm;
		$form->setAttribute('action', $this->url('cms', array('controller' => 'index', 'action' => 'site-settings')));
		$form->prepare();
		echo $this->form()->openTag($form);	?>
						  <fieldset>
						  <div class="alert <?php	echo $messageClass; ?>" id="userSuccessmsg" style="<?php	echo $display; ?>"> Site Setting updated sucessfully.</div>
							<div class="control-group">
								<label class="control-label" for="appId">APP ID</label>
								<div class="controls">
									<?php	/*	if($carrierDetails->fbappid != '') { 
												$carrier_fbappid = $carrierDetails->carrier_fbappid;
											} else {
												$carrier_fbappid = '';
											}	*/
											echo $this->formRow($form->get('fbappid')->setAttribute('value', '123')); ?>
								</div>
							</div>
							<div class="control-group">
								<label class="control-label" for="appKey">APP Secret Key</label>
								<div class="controls">
									<?php	/*	if($carrierDetails->carrier_fbkey != '') { 
												$carrier_fbkey = $carrierDetails->carrier_fbkey;
											} else {
												$carrier_fbkey = '';
											}	*/
											echo $this->formRow($form->get('fbkey')->setAttribute('value', '123'));	?>
								</div>
							</div>
							<div class="control-group">
								<label class="control-label" for="fbapp_name">APP Name</label>
								<div class="controls">
									<?php	/*	if($carrierDetails->carrier_fbapp_name != '') { 
												$carrier_fbapp_name = $carrierDetails->carrier_fbapp_name;
											} else {
												$carrier_fbapp_name = '';
											}	*/
											echo $this->formRow($form->get('fbapp_name')->setAttribute('value', '123'));	?>
								</div>
							</div>
							<div class="control-group">
								<label class="control-label" for="fbpage">Facebook Page URL</label>
								<div class="controls">
									<?php	/*	if($carrierDetails->carrier_fb_page != '') { 
												$carrier_fb_page = $carrierDetails->carrier_fb_page;
											} else {
												$carrier_fb_page = '';
											}	*/
											echo $this->formRow($form->get('fb_page')->setAttribute('value', 'https://facebook.com/testpage'));	?>
								</div>
							</div>
							<div class="control-group">
								<label class="control-label" for="timezone">Time Zone</label>
								<div class="controls">
								  <?php	echo $this->formRow($form->get('timezone')->setAttributes(array('value' => '0', 'style' => 'width:450px;')));	?>
								</div>
							</div>
							<div class="form-actions">
								<?php	echo $this->formRow($form->get('submit')); ?>
							</div>
						  </fieldset>
						<?php	echo $this->form()->closeTag();	?>
					</div>
				</div><!--/span-->
			</div><!--/row-->
<script type="text/javascript">
	$(document).ready(function(){
		$('div.radio').css({'margin-left':'70px'});
		$('.inline').css({'font-size':'12px'});
	});
	function showRadio() {
		$('div #uniform-undefined').each(function(){
			if($(this).children().children().hasClass('newupload')) {
				$(this).find('.checked').removeAttr('class');
			} 
		});
		
		$('.newupload').each(function(){
			$(this).removeAttr('checked');
		});
		
		if($("#root_label").length > 0) {
			$("#root_label").children().children().addClass('checked');
			$("#root_label").children().children().children().attr('checked', 'checked');
		}
	}
	
	function clickDiv(div) {
		$('#'+div).parent().click();
	}
</script>
