                    <dl class="row videoList">

                        <dd class="col-md-4 col-xs-12 videoFrame">

                            <div class="row">
                                <div class="col-md-12 col-xs-6">
                                    <div class="video">
                                        <img src="/Front/img/video1.png" alt="">
                                        <!--<iframe src="http://youtube.com/embed/m4cgLL8JaVI?rel=0" frameborder="0" allowfullscreen></iframe>-->
                                    </div>
                                </div>
                                <div class="col-md-12 col-xs-6">
                                    <h4><a href="http://vimeo.com/75542539">How bad do you want it?</a></h4>

                                    <div class="row">
                                        <div class="col-md-4 col-xs-12 pull-right">
                                            <ul class="likes">
                                                <li><a href="#" class="like"><i class="fa fa-2x fa-thumbs-up"></i></a></li>
                                                <li><a href="#" class="dislike"><i class="fa fa-2x fa-thumbs-down"></i></a></li>
                                            </ul>
                                        </div>
                                        <div class="col-md-8 col-xs-12 pull-left">
                                            <ul class="users"> 
                                                <li><a href="#"><img src="/Front/img/user01.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li><a href="#"><img src="/Front/img/user02.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li><a href="#"><img src="/Front/img/user03.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li class="more"><a href="#">20+</a></li>
                                            </ul>                                                
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </dd>

                        <dd class="col-md-4 col-xs-12 videoFrame">

                            <div class="row">
                                <div class="col-md-12 col-xs-6">
                                    <div class="video">
                                        <img src="/Front/img/video2.png" alt="">
                                        <!--<iframe src="http://youtube.com/embed/m4cgLL8JaVI?rel=0" frameborder="0" allowfullscreen></iframe>-->
                                    </div>
                                </div>
                                <div class="col-md-12 col-xs-6">
                                    <h4><a href="http://vimeo.com/75542539">How bad do you want it?</a></h4>

                                    <div class="row">
                                        <div class="col-md-4 col-xs-12 pull-right">
                                            <ul class="likes">
                                                <li><a href="#" class="like"><i class="fa fa-2x fa-thumbs-up"></i></a></li>
                                                <li><a href="#" class="dislike"><i class="fa fa-2x fa-thumbs-down"></i></a></li>
                                            </ul>
                                        </div>
                                        <div class="col-md-8 col-xs-12 pull-left">
                                            <ul class="users"> 
                                                <li><a href="#"><img src="/Front/img/user01.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li><a href="#"><img src="/Front/img/user02.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li><a href="#"><img src="/Front/img/user03.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li class="more"><a href="#">20+</a></li>
                                            </ul>                                                
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </dd>

                        <dd class="col-md-4 col-xs-12 videoFrame">

                            <div class="row">
                                <div class="col-md-12 col-xs-6">
                                    <div class="video">
                                        <img src="/Front/img/video1.png" alt="">
                                        <!--<iframe src="http://youtube.com/embed/m4cgLL8JaVI?rel=0" frameborder="0" allowfullscreen></iframe>-->
                                    </div>
                                </div>
                                <div class="col-md-12 col-xs-6">
                                    <h4><a href="http://vimeo.com/75542539">How bad do you want it?</a></h4>

                                    <div class="row">
                                        <div class="col-md-4 col-xs-12 pull-right">
                                            <ul class="likes">
                                                <li><a href="#" class="like"><i class="fa fa-2x fa-thumbs-up"></i></a></li>
                                                <li><a href="#" class="dislike"><i class="fa fa-2x fa-thumbs-down"></i></a></li>
                                            </ul>
                                        </div>
                                        <div class="col-md-8 col-xs-12 pull-left">
                                            <ul class="users"> 
                                                <li><a href="#"><img src="/Front/img/user01.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li><a href="#"><img src="/Front/img/user02.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li><a href="#"><img src="/Front/img/user03.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li class="more"><a href="#">20+</a></li>
                                            </ul>                                                
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </dd>

                        <dd class="col-md-4 col-xs-12 videoFrame">

                            <div class="row">
                                <div class="col-md-12 col-xs-6">
                                    <div class="video">
                                        <img src="/Front/img/video2.png" alt="">
                                        <!--<iframe src="http://youtube.com/embed/m4cgLL8JaVI?rel=0" frameborder="0" allowfullscreen></iframe>-->
                                    </div>
                                </div>
                                <div class="col-md-12 col-xs-6">
                                    <h4><a href="http://vimeo.com/75542539">How bad do you want it?</a></h4>

                                    <div class="row">
                                        <div class="col-md-4  col-xs-12 pull-right">
                                            <ul class="likes">
                                                <li><a href="#" class="like"><i class="fa fa-2x fa-thumbs-up"></i></a></li>
                                                <li><a href="#" class="dislike"><i class="fa fa-2x fa-thumbs-down"></i></a></li>
                                            </ul>
                                        </div>
                                        <div class="col-md-8  col-xs-12 pull-left">
                                            <ul class="users"> 
                                                <li><a href="#"><img src="/Front/img/user01.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li><a href="#"><img src="/Front/img/user02.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li><a href="#"><img src="/Front/img/user03.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li class="more"><a href="#">20+</a></li>
                                            </ul>                                                
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </dd>

                        <dd class="col-md-4 col-xs-12 videoFrame">

                            <div class="row">
                                <div class="col-md-12 col-xs-6">
                                    <div class="video">
                                        <img src="/Front/img/video1.png" alt="">
                                        <!--<iframe src="http://youtube.com/embed/m4cgLL8JaVI?rel=0" frameborder="0" allowfullscreen></iframe>-->
                                    </div>
                                </div>
                                <div class="col-md-12 col-xs-6">
                                    <h4><a href="http://vimeo.com/75542539">How bad do you want it?</a></h4>

                                    <div class="row">
                                        <div class="col-md-4  col-xs-12 pull-right">
                                            <ul class="likes">
                                                <li><a href="#" class="like"><i class="fa fa-2x fa-thumbs-up"></i></a></li>
                                                <li><a href="#" class="dislike"><i class="fa fa-2x fa-thumbs-down"></i></a></li>
                                            </ul>
                                        </div>
                                        <div class="col-md-8  col-xs-12 pull-left">
                                            <ul class="users"> 
                                                <li><a href="#"><img src="/Front/img/user01.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li><a href="#"><img src="/Front/img/user02.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li><a href="#"><img src="/Front/img/user03.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li class="more"><a href="#">20+</a></li>
                                            </ul>                                                
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </dd>

                        <dd class="col-md-4 col-xs-12 videoFrame">

                            <div class="row">
                                <div class="col-md-12 col-xs-6">
                                    <div class="video">
                                        <img src="/Front/img/video2.png" alt="">
                                        <!--<iframe src="http://youtube.com/embed/m4cgLL8JaVI?rel=0" frameborder="0" allowfullscreen></iframe>-->
                                    </div>
                                </div>
                                <div class="col-md-12 col-xs-6">
                                    <h4><a href="http://vimeo.com/75542539">How bad do you want it?</a></h4>

                                    <div class="row">
                                        <div class="col-md-4  col-xs-12 pull-right">
                                            <ul class="likes">
                                                <li><a href="#" class="like"><i class="fa fa-2x fa-thumbs-up"></i></a></li>
                                                <li><a href="#" class="dislike"><i class="fa fa-2x fa-thumbs-down"></i></a></li>
                                            </ul>
                                        </div>
                                        <div class="col-md-8  col-xs-12 pull-left">
                                            <ul class="users"> 
                                                <li><a href="#"><img src="/Front/img/user01.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li><a href="#"><img src="/Front/img/user02.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li><a href="#"><img src="/Front/img/user03.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li class="more"><a href="#">20+</a></li>
                                            </ul>                                                
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </dd>

                        <dd class="col-md-4 col-xs-12 videoFrame">

                            <div class="row">
                                <div class="col-md-12 col-xs-6">
                                    <div class="video">
                                        <img src="/Front/img/video1.png" alt="">
                                        <!--<iframe src="http://youtube.com/embed/m4cgLL8JaVI?rel=0" frameborder="0" allowfullscreen></iframe>-->
                                    </div>
                                </div>
                                <div class="col-md-12 col-xs-6">
                                    <h4><a href="http://vimeo.com/75542539">How bad do you want it?</a></h4>

                                    <div class="row">
                                        <div class="col-md-4  col-xs-12 pull-right">
                                            <ul class="likes">
                                                <li><a href="#" class="like"><i class="fa fa-2x fa-thumbs-up"></i></a></li>
                                                <li><a href="#" class="dislike"><i class="fa fa-2x fa-thumbs-down"></i></a></li>
                                            </ul>
                                        </div>
                                        <div class="col-md-8  col-xs-12 pull-left">
                                            <ul class="users"> 
                                                <li><a href="#"><img src="/Front/img/user01.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li><a href="#"><img src="/Front/img/user02.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li><a href="#"><img src="/Front/img/user03.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li class="more"><a href="#">20+</a></li>
                                            </ul>                                                
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </dd>

                        <dd class="col-md-4 col-xs-12 videoFrame">

                            <div class="row">
                                <div class="col-md-12 col-xs-6">
                                    <div class="video">
                                        <img src="/Front/img/video2.png" alt="">
                                        <!--<iframe src="http://youtube.com/embed/m4cgLL8JaVI?rel=0" frameborder="0" allowfullscreen></iframe>-->
                                    </div>
                                </div>
                                <div class="col-md-12 col-xs-6">
                                    <h4><a href="http://vimeo.com/75542539">How bad do you want it?</a></h4>

                                    <div class="row">
                                        <div class="col-md-4  col-xs-12 pull-right">
                                            <ul class="likes">
                                                <li><a href="#" class="like"><i class="fa fa-2x fa-thumbs-up"></i></a></li>
                                                <li><a href="#" class="dislike"><i class="fa fa-2x fa-thumbs-down"></i></a></li>
                                            </ul>
                                        </div>
                                        <div class="col-md-8  col-xs-12 pull-left">
                                            <ul class="users"> 
                                                <li><a href="#"><img src="/Front/img/user01.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li><a href="#"><img src="/Front/img/user02.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li><a href="#"><img src="/Front/img/user03.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li class="more"><a href="#">20+</a></li>
                                            </ul>                                                
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </dd>

                        <dd class="col-md-4 col-xs-12 videoFrame">

                            <div class="row">
                                <div class="col-md-12 col-xs-6">
                                    <div class="video">
                                        <img src="/Front/img/video1.png" alt="">
                                    </div>
                                </div>
                                <div class="col-md-12 col-xs-6">
                                    <h4><a href="http://vimeo.com/75542539">How bad do you want it?</a></h4>

                                    <div class="row">
                                        <div class="col-md-4  col-xs-12 pull-right">
                                            <ul class="likes">
                                                <li><a href="#" class="like"><i class="fa fa-2x fa-thumbs-up"></i></a></li>
                                                <li><a href="#" class="dislike"><i class="fa fa-2x fa-thumbs-down"></i></a></li>
                                            </ul>
                                        </div>
                                        <div class="col-md-8  col-xs-12 pull-left">
                                            <ul class="users"> 
                                                <li><a href="#"><img src="/Front/img/user01.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li><a href="#"><img src="/Front/img/user02.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li><a href="#"><img src="/Front/img/user03.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li class="more"><a href="#">20+</a></li>
                                            </ul>                                                
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </dd>

                        <dd class="col-md-4 col-xs-12 videoFrame">

                            <div class="row">
                                <div class="col-md-12 col-xs-6">
                                    <div class="video">
                                        <img src="/Front/img/video2.png" alt="">
                                    </div>
                                </div>
                                <div class="col-md-12 col-xs-6">
                                    <h4><a href="http://vimeo.com/75542539">How bad do you want it?</a></h4>

                                    <div class="row">
                                        <div class="col-md-4  col-xs-12 pull-right">
                                            <ul class="likes">
                                                <li><a href="#" class="like"><i class="fa fa-2x fa-thumbs-up"></i></a></li>
                                                <li><a href="#" class="dislike"><i class="fa fa-2x fa-thumbs-down"></i></a></li>
                                            </ul>
                                        </div>
                                        <div class="col-md-8  col-xs-12 pull-left">
                                            <ul class="users"> 
                                                <li><a href="#"><img src="/Front/img/user01.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li><a href="#"><img src="/Front/img/user02.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li><a href="#"><img src="/Front/img/user03.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li class="more"><a href="#">20+</a></li>
                                            </ul>                                                
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </dd>

                        <dd class="col-md-4 col-xs-12 videoFrame">

                            <div class="row">
                                <div class="col-md-12 col-xs-6">
                                    <div class="video">
                                        <img src="/Front/img/video1.png" alt="">
                                    </div>
                                </div>
                                <div class="col-md-12 col-xs-6">
                                    <h4><a href="http://vimeo.com/75542539">How bad do you want it?</a></h4>

                                    <div class="row">
                                        <div class="col-md-4  col-xs-12 pull-right">
                                            <ul class="likes">
                                                <li><a href="#" class="like"><i class="fa fa-2x fa-thumbs-up"></i></a></li>
                                                <li><a href="#" class="dislike"><i class="fa fa-2x fa-thumbs-down"></i></a></li>
                                            </ul>
                                        </div>
                                        <div class="col-md-8  col-xs-12 pull-left">
                                            <ul class="users"> 
                                                <li><a href="#"><img src="/Front/img/user01.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li><a href="#"><img src="/Front/img/user02.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li><a href="#"><img src="/Front/img/user03.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li class="more"><a href="#">20+</a></li>
                                            </ul>                                                
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </dd>

                        <dd class="col-md-4 col-xs-12 videoFrame">

                            <div class="row">
                                <div class="col-md-12 col-xs-6">
                                    <div class="video">
                                        <img src="/Front/img/video2.png" alt="">
                                    </div>
                                </div>
                                <div class="col-md-12 col-xs-6">
                                    <h4><a href="http://vimeo.com/75542539">How bad do you want it?</a></h4>

                                    <div class="row">
                                        <div class="col-md-4  col-xs-12 pull-right">
                                            <ul class="likes">
                                                <li><a href="#" class="like"><i class="fa fa-2x fa-thumbs-up"></i></a></li>
                                                <li><a href="#" class="dislike"><i class="fa fa-2x fa-thumbs-down"></i></a></li>
                                            </ul>
                                        </div>
                                        <div class="col-md-8  col-xs-12 pull-left">
                                            <ul class="users"> 
                                                <li><a href="#"><img src="/Front/img/user01.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li><a href="#"><img src="/Front/img/user02.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li><a href="#"><img src="/Front/img/user03.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                                                <li class="more"><a href="#">20+</a></li>
                                            </ul>                                                
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </dd>

                        <dd class="clearfix videoMore">
                            <a class="btn btn-default" href="#">show 18 more</a>
                        </dd>
                    </dl>
