<?php	if(is_array($records) && count($records) > 0) {
			foreach($records as $key => $value) {	?>
	<dd class="col-md-4 col-xs-12 videoFrame">
		<div class="row">
        	<div class="col-md-12 col-xs-6">
            	<div class="video">
					<a href="<?php	echo $this->url('front', array('controller' => 'search', 'action' => 'view-video', 'id' => base64_encode((string)$value['_id']))); ?>" title="<?php echo $value['media_title']; ?>">
                     <img src="http://img.youtube.com/vi/<?php echo $this->customurl($value['media_url'], 'fetchYoutubeID'); ?>/0.jpg" alt="<?php echo $value['media_title']; ?>" >
					 <span class="play-btn"><i class="fa fa-play fa-2"></i></span>
					</a>
                     <!--<iframe src="http://youtube.com/embed/m4cgLL8JaVI?rel=0" frameborder="0" allowfullscreen></iframe>-->
				</div>
			</div>
            <div class="col-md-12 col-xs-6">
				<h4><a title="<?php echo $value['media_title']; ?>" href="<?php	echo $this->url('front', array('controller' => 'search', 'action' => 'view-video', 'id' => base64_encode((string)$value['_id']))); ?>"><?php	echo $this->text($value['media_title'], 25, 'displayText'); ?></a></h4>
            	<!-- <h4 ><a href="http://vimeo.com/75542539"><?php	echo $this->text($value['media_title'], 25, 'displayText'); ?></a></h4> -->
				<div class="row">
                	<div class="col-md-4 col-xs-12 pull-right">
                    	<ul class="likes">
                        	<li><a href="#" class="like" onclick='dovote(1, "<?php	echo base64_encode((string)$value['_id']); ?>", "<?php echo $value['media_title']; ?>");return false;'><i class="fa fa-2x fa-thumbs-up"></i></a></li>
                            <li><a href="#" class="dislike" onclick='dovote(2, "<?php	echo base64_encode((string)$value['_id']); ?>", "<?php echo $value['media_title']; ?>");return false;'><i class="fa fa-2x fa-thumbs-down"></i></a></li>
						</ul>
					</div>
                    <div class="col-md-8 col-xs-12 pull-left">
                    	<ul class="users"> 
                        	<li><a href="#"><img src="/Front/img/user01.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                            <li><a href="#"><img src="/Front/img/user02.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                            <li><a href="#"><img src="/Front/img/user03.jpg" width="30" height="30" alt="user" title="user name"></a></li>
                            <li class="more"><a href="#">20+</a></li>
						</ul>                                                
					</div>
				</div>
			</div>
		</div>
	</dd>
<?php		}
			if(($totalRecords - ($page * PERPAGE)) > 0) {	?>
				<dd class="clearfix videoMore" id="more_videos">
                    <p class="btn btn-default" onclick="loadVideos(1);">show 18 more</p>
                </dd>
<?php		} else { ?>
				<dd class="clearfix videoMore" id="no_more_videos">
                    <p class="btn nomore-btn">No more videos</p>
                </dd>
<?php		}
		}	?>
<script type="text/javascript">
	if($('#video_count').length > 0) {
		$('#video_count').html('<?php echo $totalRecords; ?> videos found');
	}
</script>